// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcSensC
double calcSensC(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcSensC(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcSensC(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcSpecC
double calcSpecC(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcSpecC(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcSpecC(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcPrecC
double calcPrecC(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcPrecC(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcPrecC(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcESensC
double calcESensC(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcESensC(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcESensC(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcESpecC
double calcESpecC(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcESpecC(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcESpecC(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcEPrecC
double calcEPrecC(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcEPrecC(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcEPrecC(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcSensD
double calcSensD(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcSensD(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcSensD(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcSpecD
double calcSpecD(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcSpecD(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcSpecD(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcPrecD
double calcPrecD(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcPrecD(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcPrecD(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcESensD
double calcESensD(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcESensD(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcESensD(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcESpec
double calcESpec(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcESpec(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcESpec(h, m));
    return rcpp_result_gen;
END_RCPP
}
// calcEPrecD
double calcEPrecD(NumericMatrix h, NumericMatrix m);
RcppExport SEXP _CAMO_calcEPrecD(SEXP hSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(calcEPrecD(h, m));
    return rcpp_result_gen;
END_RCPP
}
// MCMC
Rcpp::List MCMC(NumericVector Z, int iteration, double const gamma);
RcppExport SEXP _CAMO_MCMC(SEXP ZSEXP, SEXP iterationSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< double const >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC(Z, iteration, gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CAMO_calcSensC", (DL_FUNC) &_CAMO_calcSensC, 2},
    {"_CAMO_calcSpecC", (DL_FUNC) &_CAMO_calcSpecC, 2},
    {"_CAMO_calcPrecC", (DL_FUNC) &_CAMO_calcPrecC, 2},
    {"_CAMO_calcESensC", (DL_FUNC) &_CAMO_calcESensC, 2},
    {"_CAMO_calcESpecC", (DL_FUNC) &_CAMO_calcESpecC, 2},
    {"_CAMO_calcEPrecC", (DL_FUNC) &_CAMO_calcEPrecC, 2},
    {"_CAMO_calcSensD", (DL_FUNC) &_CAMO_calcSensD, 2},
    {"_CAMO_calcSpecD", (DL_FUNC) &_CAMO_calcSpecD, 2},
    {"_CAMO_calcPrecD", (DL_FUNC) &_CAMO_calcPrecD, 2},
    {"_CAMO_calcESensD", (DL_FUNC) &_CAMO_calcESensD, 2},
    {"_CAMO_calcESpec", (DL_FUNC) &_CAMO_calcESpec, 2},
    {"_CAMO_calcEPrecD", (DL_FUNC) &_CAMO_calcEPrecD, 2},
    {"_CAMO_MCMC", (DL_FUNC) &_CAMO_MCMC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CAMO(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
