# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
calcSensC <- function(h, m) {
    .Call(`_CAMO_calcSensC`, h, m)
}

#' @export
calcSpecC <- function(h, m) {
    .Call(`_CAMO_calcSpecC`, h, m)
}

#' @export
calcPrecC <- function(h, m) {
    .Call(`_CAMO_calcPrecC`, h, m)
}

#' @export
calcESensC <- function(h, m) {
    .Call(`_CAMO_calcESensC`, h, m)
}

#' @export
calcESpecC <- function(h, m) {
    .Call(`_CAMO_calcESpecC`, h, m)
}

#' @export
calcEPrecC <- function(h, m) {
    .Call(`_CAMO_calcEPrecC`, h, m)
}

#' @export
calcSensD <- function(h, m) {
    .Call(`_CAMO_calcSensD`, h, m)
}

#' @export
calcSpecD <- function(h, m) {
    .Call(`_CAMO_calcSpecD`, h, m)
}

#' @export
calcPrecD <- function(h, m) {
    .Call(`_CAMO_calcPrecD`, h, m)
}

#' @export
calcESensD <- function(h, m) {
    .Call(`_CAMO_calcESensD`, h, m)
}

#' @export
calcESpec <- function(h, m) {
    .Call(`_CAMO_calcESpec`, h, m)
}

#' @export
calcEPrecD <- function(h, m) {
    .Call(`_CAMO_calcEPrecD`, h, m)
}

MCMC <- function(Z, iteration, gamma) {
    .Call(`_CAMO_MCMC`, Z, iteration, gamma)
}

